function [file_type,analysis_numb] = choose_file_type

    d = dialog('Units','normalized',...
        'Position',[0.45 0.45 0.2 0.2],...
        'Name','Select Source File Type:');
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Units','normalized',...
           'Position',[0.1 0.60 0.4 0.2],...
           'FontSize',10,...
           'HorizontalAlignment','left',...
           'String','File Type');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Units','normalized',...
           'Position',[0.6 0.55 0.3 0.25],...
           'FontSize',10,...
           'String',{'DICOM';'nii'},...
           'Callback',@popup_callback);
       
   
       txtanalysis = uicontrol('Parent',d,...
           'Style','text',...
           'Units','normalized',...
           'HorizontalAlignment','left',...
           'Position',[0.1 0.40 0.6 0.2],...
           'FontSize',10,...
           'String','Analysis Slice Number');
       
       editbox_anlysis = uicontrol('Parent',d,...
           'Style','edit',...
           'Units','normalized',...
           'Position',[0.6 0.50 0.3 0.14],...
           'Max',1,...
           'String','0',...
           'FontSize',10,...
           'Callback',@editboxanalysis_callback);
       
       
       
    btn = uicontrol('Parent',d,...
           'Units','normalized',...
           'Position',[0.35 0.20 0.3 0.15],...
           'String','Next',...
           'FontSize',10,...
           'Callback','delete(gcf)');
       
    file_type = 'DICOM';
    analysis_numb=9;   
    % Wait for d to close before running to completion
    uiwait(d);
   
       function popup_callback(popup,callbackdata)
          idx = popup.Value;
          popup_items = popup.String;
          % This code uses dot notation to get properties.
          % Dot notation runs in R2014b and later.
          % For R2014a and earlier:
          % idx = get(popup,'Value');
          % popup_items = get(popup,'String');
          file_type = char(popup_items(idx,:));
       end
   
   function editboxanalysis_callback(editbox_anlysis, callbackdata)        
        analysis_numb = editbox_anlysis.String;
        analysis_numb=str2num(analysis_numb);
    end
   
end