function analysis_method = choose_analysis_method
d = dialog('Units','normalized',...
        'Position',[0.45 0.45 0.2 0.2],...
        'Name','Select Analysis Method:');
txt = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.0 0.50 0.4 0.2],...
    'FontSize',10,...
    'String','Analysis Method');
popup = uicontrol('Parent',d,...
    'Style','popup',...
    'Units','normalized',...
    'Tag','popmethod',...
    'FontSize',10,...
    'Position',[0.5 0.50 0.4 0.2],...
    'String',{'Biexp', 'Simplified IVIM','Mix','fix D_star','Sove 3 variables once'},...
    'Callback',@popup_method);

btn = uicontrol('Parent',d,...
    'Units','normalized',...
    'Position',[0.3 0.20 0.4 0.2],...
    'FontSize',10,...
    'String','OK',...
    'Callback','delete(gcf)');
analysis_method=[];
uiwait(d);
    function popup_method(popup,callbackdata)
        idx = popup.Value;
        popup_items = popup.String;
        analysis_method = char(popup_items(idx,:));
    end
end