function y=Generate_TestPattern()
d = dialog('Units','normalized','Position',[0.45 0.45 0.3 0.30],'Name','Test Parten');
txt_Normal = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.27 0.85 0.2 0.1],...
    'HorizontalAlignment','left',...
    'FontSize',10,...
    'String','Normal Tissue');
txt_Cancer = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.48 0.85 0.2 0.1],...
    'HorizontalAlignment','left',...
    'FontSize',10,...
    'String','Cancer Tissue');

txt_f = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.20 0.75 0.1 0.1],...
    'HorizontalAlignment','left',...
    'FontSize',10,...
    'String','F=');
edit_f_normal = uicontrol('Parent',d,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.30 0.75 0.1 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',10,...
    'Value',0.0,...
    'String','0.0',...
    'Tag','edif_f_normal');

edit_f_cancer = uicontrol('Parent',d,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.50 0.75 0.1 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',10,...
    'Value',0.3,...
    'String','0.3',...
    'Tag','edit_f_cancer');



txt_D = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.20 0.65 0.1 0.1],...
    'HorizontalAlignment','left',...
    'FontSize',10,...
    'String','D=');

edit_D_normal = uicontrol('Parent',d,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.30 0.65 0.1 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',10,...
    'Value',0,...
    'String','0',...
    'Tag','edit_D_normal');
edit_D_cancer = uicontrol('Parent',d,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.50 0.65 0.1 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',10,...
    'Value',2.5*10^(-3),...
    'String','2.5',...
    'Tag','edit_D_cancer');

edit_D_exp = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.6 0.63 0.1 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',10,...
    'String','10^(-3)');




txt_DS = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.20 0.55 0.1 0.1],...
    'HorizontalAlignment','left',...
    'FontSize',10,...
    'String','D*=');
edit_DS_normal = uicontrol('Parent',d,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.30 0.55 0.1 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',10,...
    'Value',0,...
    'String','0',...
    'Tag','edit_DS_normal');
edit_DS_cancer = uicontrol('Parent',d,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.50 0.55 0.1 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',10,...
    'Value',50,...
    'String','50',...
    'Tag','edit_DS_cancer');
text_DS_exp = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.6 0.53 0.1 0.1],...
    'HorizontalAlignment','center',...
    'FontSize',10,...
    'String','10^(-3)');






btn = uicontrol('Parent',d,...
    'Units','normalized',...
    'Position',[0.35 0.1 0.3 0.2],...
    'String','Close',...
    'FontSize',10,...
    'Callback',@button_callback);
%uiwait(d)


function button_callback(source,callbackdata)
    h=findobj('Tag','edif_f_normal');
    norm_tissue.f=str2num(get(h,'String'));    
    h=findobj('Tag','edit_f_cancer');
    cancer_tissue.f=str2num(get(h,'String'));    
    
    
    h=findobj('Tag','edit_D_normal');
    norm_tissue.D=str2num(get(h,'String'))*10^(-3);    
    h=findobj('Tag','edit_D_cancer');
    cancer_tissue.D=str2num(get(h,'String'))*10^(-3);    
    
    
    
    h=findobj('Tag','edit_DS_normal');
    norm_tissue.DS=str2num(get(h,'String'))*10^(-3);    
    h=findobj('Tag','edit_DS_cancer');
    cancer_tissue.DS=str2num(get(h,'String'))*10^(-3);
    
    
    
    BW=zeros(256,256);
    BW(100:120,170:200)=1;
%     BW=ones(256,256);
    h=findobj('Tag','Load_ROI');
    set(h,'UserData',BW);
    
    S0=1500;
    bval=[10 20 30 40 50 80 120 150 200 400 700 800 1000 0];
    Image=zeros(256,256,length(bval));
    f_matrix=ones(256,256)*norm_tissue.f;
    D_matrix=ones(256,256)*norm_tissue.D;
    DS_matrix=ones(256,256)*norm_tissue.DS;
    
    index=find(BW==1);
    f_matrix(index)=cancer_tissue.f;
    D_matrix(index)=cancer_tissue.D;
    DS_matrix(index)=cancer_tissue.DS;
    
    for(i=1:length(bval))
        %     Image(:,:,i)=(f_matrix.*exp(-bval(i).*DS_matrix)+((1-f_matrix).*exp(-bval(i).*D_matrix)))*S0+0.02*random('Normal',0,1);
        Image(:,:,i)=(f_matrix.*exp(-bval(i).*DS_matrix)+((1-f_matrix).*exp(-bval(i).*D_matrix)))*S0;
        %     Image(:,:,i)=((1-f_matrix).*exp(-bval(i).*D_matrix))*S0+0.02*random('Normal',0,1);
        %     Image(:,:,i)=((1-f_matrix).*exp(-bval(i).*D_matrix))*S0;
    end
    
    metadata=[];
    user_value.Image=Image;
    user_value.bval=bval;
    user_value.metadata=metadata;
    h=findobj('Tag','File_Load');
    set(h,'UserData',user_value);
    
    
    
    
    
    
    delete(gcf);    
end


% norm_tissue.f=0;
% cancer_tissue.f=0.2;
% 
% norm_tissue.D=0;
% cancer_tissue.D=2.5*10^(-3);
% 
% norm_tissue.DS=0;
% cancer_tissue.DS=50*10^(-3);




end




    




