function bval = Partial_B
d = dialog('Position',[200 300 250 150],'Name','Partial B:');
txtbval = uicontrol('Parent',d,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.1 0.8 0.2 0.1],...
    'String','b_value');

editbox_bval = uicontrol('Parent',d,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.1 0.4 0.2 0.3],...
    'Max',2,...
    'String','0',...
    'Callback',@editboxbval_callback);

btn = uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','OK',...
           'Callback','delete(gcf)');
uiwait(d)
    function editboxbval_callback(editbox_bval, callbackdata)        
        bval = str2num(editbox_bval.String);        
    end
end



